export { default as Layout } from './Layout/layout';
export {default as Navbar} from './navbar/navbar'
export {default as Banner} from './Banner/banner'
export {default as NewsSlider} from './news-slider/news-slider'
export {default as Footer} from './footer/footer'
export {default as BreadCrumb} from './bread-crumb/bread-crumb'
export {default as NotFound} from './not-found/not-found'
export {default as HeadBanner} from './head-banner/head-banner'
export {default as MyInput} from './Input/Input'
export {default as Button} from './Button/button'
export {default as ChackPolis} from './chack-polis/chack-polis'
export {default as BannerLegal } from './Banner-legal/banner-legal'
export {default as Acc } from './accardion-block/accardion-block'
export {default as Modal} from './modal/modal'