export * from './common'
export * from './main-catalog'
export * from './new/index'
export * from './personal-area/index'
export * from './renewal-polis/index'
export * from './auth/index'
export * from './legal-block/index'
export * from './Forms/index'